'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_annee_fiscale
    Public Property id_anneefiscale As Long
    Public Property description As String
    Public Property Debut As Nullable(Of Date)
    Public Property fin As Nullable(Of Date)
    Public Property Createdby As String
    Public Property DateCreated As Nullable(Of Date)
    Public Property ModifBy As String
    Public Property DateModif As Nullable(Of Date)
    Public Property id_Municipalite As Nullable(Of Long)

    Public Overridable Property tbl_Patente As ICollection(Of tbl_Patente) = New HashSet(Of tbl_Patente)

End Class
Partial Public Class Tbl_architecte
    Public Property ID_architecte As Long
    Public Property Nom As String
    Public Property Prenom As String
    Public Property CIN As String
    Public Property NIF As String
    Public Property Date_naissance As Nullable(Of Date)
    Public Property adresse As String
    Public Property email As String
    Public Property telephone As String
    Public Property sexe As String
    Public Property CreatedBy As String
    Public Property DateCreated As Nullable(Of Date)
    Public Property ModifBy As String
    Public Property DateModif As Nullable(Of Date)
    Public Property Id_uniteGeo As Nullable(Of Long)

End Class
Partial Public Class tbl_Entreprise
    Public Property Id_entreprise As Long
    Public Property Nom_entreprise As String
    Public Property Noms_anterieurs As String
    Public Property Forme_juridique As Nullable(Of Long)
    Public Property Tel1 As String
    Public Property Tel2 As String
    Public Property descritption As String
    Public Property Adresse As String
    Public Property autreAdresse As String
    Public Property DateCreated As Date
    Public Property CreatedBy As String
    Public Property DateModif As Nullable(Of Date)
    Public Property ModifBy As String
    Public Property Fondateur As String
    Public Property DebutdateFonctionnement As Nullable(Of Date)

    Public Overridable Property Tbl_forme_juridique As Tbl_forme_juridique
    Public Overridable Property tbl_Patente As ICollection(Of tbl_Patente) = New HashSet(Of tbl_Patente)
    Public Overridable Property Tbl_Inspection As ICollection(Of Tbl_Inspection) = New HashSet(Of Tbl_Inspection)

End Class
Partial Public Class Tbl_Event
    Public Property ID_Evaluation As Long
    Public Property ID_monument As Nullable(Of Long)
    Public Property Commentaires As String
    Public Property CreatedBy As String
    Public Property DateCreated As Nullable(Of Date)
    Public Property ModifBy As String
    Public Property DateModif As Nullable(Of Date)
    Public Property ID_Institution As Nullable(Of Long)
    Public Property DateEffectuee As Nullable(Of Date)
    Public Property DateDebut As Nullable(Of Date)
    Public Property DateFin As Nullable(Of Date)
    Public Property Sujet As String
    Public Property Description As String
    Public Property RecurrenceParentID As Nullable(Of Long)
    Public Property RecurrenceRule As String
    Public Property ID_Statut As Nullable(Of Short)

    Public Overridable Property tbl_monument As tbl_monument
    Public Overridable Property Tbl_Statut_Evenement As Tbl_Statut_Evenement

End Class
Partial Public Class Tbl_forme_juridique
    Public Property ID_Forme As Long
    Public Property Nom_forme As String
    Public Property descriptition As String
    Public Property CreatedBy As String
    Public Property DateCreated As Nullable(Of Date)
    Public Property ModifBy As String
    Public Property DateModif As Nullable(Of Date)

    Public Overridable Property tbl_Entreprise As ICollection(Of tbl_Entreprise) = New HashSet(Of tbl_Entreprise)

End Class
Partial Public Class tbl_formulaire_arbattage
    Public Property Id_formulaire As Long
    Public Property id_statut As Nullable(Of Short)
    Public Property id_personne As Nullable(Of Long)
    Public Property date_demande As Nullable(Of Date)

    Public Overridable Property Tbl_Personne As Tbl_Personne
    Public Overridable Property tbl_statut_arbattage As tbl_statut_arbattage

End Class
Partial Public Class Tbl_Inspection
    Public Property id_Inspection As Long
    Public Property Id_entreprise As Nullable(Of Long)
    Public Property details_entrepise As String
    Public Property details_produit As String
    Public Property Adresse As String
    Public Property autreAdresse As String
    Public Property nom_produit As String
    Public Property DateCreated As Nullable(Of Date)
    Public Property CreatedBy As String
    Public Property ModifBy As String
    Public Property id_produit As Nullable(Of Long)

    Public Overridable Property Tbl_Produit As Tbl_Produit
    Public Overridable Property tbl_Entreprise As tbl_Entreprise

End Class
Partial Public Class tbl_mairie
    Public Property Id_mairie As Long
    Public Property nom_mairie As String
    Public Property description As String
    Public Property DateCreated As Nullable(Of Date)
    Public Property CreatedBy As String
    Public Property DateModif As Nullable(Of Date)
    Public Property ModifBy As String

    Public Overridable Property tbl_monument As ICollection(Of tbl_monument) = New HashSet(Of tbl_monument)
    Public Overridable Property tbl_Patente As ICollection(Of tbl_Patente) = New HashSet(Of tbl_Patente)
    Public Overridable Property Tbl_Personne As ICollection(Of Tbl_Personne) = New HashSet(Of Tbl_Personne)

End Class
Partial Public Class tbl_monument
    Public Property Id_monument As Long
    Public Property nom_monument As String
    Public Property description As String
    Public Property latitude As Nullable(Of Double)
    Public Property longitude As Nullable(Of Double)
    Public Property id_mairie As Nullable(Of Long)

    Public Overridable Property tbl_mairie As tbl_mairie
    Public Overridable Property Tbl_Event As ICollection(Of Tbl_Event) = New HashSet(Of Tbl_Event)

End Class
Partial Public Class Tbl_nombre
    Public Property ID As Long
    Public Property nombre As Nullable(Of Short)
    Public Property descriptition As String
    Public Property CreatedBy As String
    Public Property DateCreated As Nullable(Of Date)
    Public Property ModifBy As String
    Public Property DateModif As Nullable(Of Date)

End Class
Partial Public Class tbl_Patente
    Public Property ID_Patente As Long
    Public Property ID_Entreprise As Nullable(Of Long)
    Public Property Id_AnneeFiscal As Nullable(Of Long)
    Public Property Id_commune As Nullable(Of Long)
    Public Property MasseSalariale As Nullable(Of Decimal)
    Public Property ChiffresAffaires As Nullable(Of Decimal)
    Public Property Commentaire As String
    Public Property id_Facture As Nullable(Of Long)
    Public Property DateCreated As Nullable(Of Date)
    Public Property CreatedBy As String
    Public Property DateModif As Nullable(Of Date)
    Public Property ModifBy As String
    Public Property Montant As Nullable(Of Decimal)
    Public Property id_secteur As Nullable(Of Long)
    Public Property id_statut As Nullable(Of Long)
    Public Property id_mairie As Nullable(Of Long)

    Public Overridable Property tbl_annee_fiscale As tbl_annee_fiscale
    Public Overridable Property tbl_Entreprise As tbl_Entreprise
    Public Overridable Property Tbl_secteur_activite As Tbl_secteur_activite
    Public Overridable Property Tbl_statut_patente As Tbl_statut_patente
    Public Overridable Property tbl_mairie As tbl_mairie

End Class
Partial Public Class Tbl_Personne
    Public Property ID_Personne As Long
    Public Property Nom As String
    Public Property Prenom As String
    Public Property CIN As String
    Public Property NIF As String
    Public Property Date_naissance As Nullable(Of Date)
    Public Property adresse As String
    Public Property email As String
    Public Property telephone As String
    Public Property sexe As String
    Public Property CreatedBy As String
    Public Property DateCreated As Nullable(Of Date)
    Public Property ModifBy As String
    Public Property DateModif As Nullable(Of Date)
    Public Property Id_uniteGeo As Nullable(Of Long)
    Public Property id_mairie As Nullable(Of Long)

    Public Overridable Property tbl_formulaire_arbattage As ICollection(Of tbl_formulaire_arbattage) = New HashSet(Of tbl_formulaire_arbattage)
    Public Overridable Property tbl_mairie As tbl_mairie

End Class
Partial Public Class Tbl_Produit
    Public Property id_produit As Long
    Public Property nom_produit As String
    Public Property CreatedBy As String
    Public Property DateModif As Nullable(Of Date)
    Public Property ModifBy As String
    Public Property DateCreated As Nullable(Of Date)
    Public Property info_produit As String

    Public Overridable Property Tbl_Inspection As ICollection(Of Tbl_Inspection) = New HashSet(Of Tbl_Inspection)

End Class
Partial Public Class tbl_raison_arbattage
    Public Property Id_raison As Short
    Public Property raison As String
    Public Property description As String
    Public Property CreatedBy As String
    Public Property DateCreated As Nullable(Of Date)
    Public Property ModifBy As String
    Public Property DateModif As Nullable(Of Date)

End Class
Partial Public Class tbl_RefNiveauGeo
    Public Property Id_NiveauGeo As Long
    Public Property DescriptionNiveau As String
    Public Property A_NiveauSup As Nullable(Of Boolean)
    Public Property Id_NiveauSup As Nullable(Of Long)
    Public Property Rang As Nullable(Of Integer)
    Public Property CreatedBy As String
    Public Property DateCreated As Date
    Public Property ModifBy As String
    Public Property DateModif As Nullable(Of Date)

    Public Overridable Property tbl_RefUniteGeo As ICollection(Of tbl_RefUniteGeo) = New HashSet(Of tbl_RefUniteGeo)

End Class
Partial Public Class tbl_RefUniteGeo
    Public Property Id_UniteGeo As Long
    Public Property DescriptionUnite As String
    Public Property Id_UniteGeoSup As Nullable(Of Long)
    Public Property Superficie As Nullable(Of Double)
    Public Property Id_NiveauGeo As Nullable(Of Long)
    Public Property LatMinCoordGPS As Nullable(Of Double)
    Public Property LonMinCoordGPS As Nullable(Of Double)
    Public Property Population As Nullable(Of Long)
    Public Property Densite As Nullable(Of Double)
    Public Property LonXCoorGPS As Nullable(Of Double)
    Public Property ValY As Nullable(Of Double)
    Public Property ValX As Nullable(Of Double)
    Public Property LatXCoorGPS As Nullable(Of Double)
    Public Property CreatedBy As String
    Public Property DateCreated As Date
    Public Property ModifBy As String
    Public Property DateModif As Nullable(Of Date)

    Public Overridable Property tbl_RefNiveauGeo As tbl_RefNiveauGeo

End Class
Partial Public Class Tbl_secteur_activite
    Public Property ID_secteur As Long
    Public Property Nom_Secteur As String
    Public Property descriptition As String
    Public Property CreatedBy As String
    Public Property DateCreated As Nullable(Of Date)
    Public Property ModifBy As String
    Public Property DateModif As Nullable(Of Date)
    Public Property Tarif As Nullable(Of Integer)

    Public Overridable Property tbl_Patente As ICollection(Of tbl_Patente) = New HashSet(Of tbl_Patente)

End Class
Partial Public Class tbl_statut_arbattage
    Public Property Id_statut_arbattage As Short
    Public Property staut As String
    Public Property description As String
    Public Property CreatedBy As String
    Public Property DateCreated As Nullable(Of Date)
    Public Property ModifBy As String
    Public Property DateModif As Nullable(Of Date)

    Public Overridable Property tbl_formulaire_arbattage As ICollection(Of tbl_formulaire_arbattage) = New HashSet(Of tbl_formulaire_arbattage)

End Class
Partial Public Class Tbl_Statut_Evenement
    Public Property ID_Statut As Short
    Public Property Statut As String
    Public Property couleur As String
    Public Property CreatedBy As String
    Public Property DateCreated As Nullable(Of Date)
    Public Property ModifBy As String
    Public Property DateModif As Nullable(Of Date)

    Public Overridable Property Tbl_Event As ICollection(Of Tbl_Event) = New HashSet(Of Tbl_Event)

End Class
Partial Public Class Tbl_statut_occupant
    Public Property ID_Statut As Long
    Public Property Statut As String
    Public Property descriptition As String
    Public Property CreatedBy As String
    Public Property DateCreated As Nullable(Of Date)
    Public Property ModifBy As String
    Public Property DateModif As Nullable(Of Date)

End Class
Partial Public Class Tbl_statut_patente
    Public Property ID_Statut As Long
    Public Property Statut As String
    Public Property descriptition As String
    Public Property CreatedBy As String
    Public Property DateCreated As Nullable(Of Date)
    Public Property ModifBy As String
    Public Property DateModif As Nullable(Of Date)

    Public Overridable Property tbl_Patente As ICollection(Of tbl_Patente) = New HashSet(Of tbl_Patente)

End Class
Partial Public Class Tbl_type_annexe
    Public Property ID_type As Long
    Public Property Type_Annexe As String
    Public Property descriptition As String
    Public Property CreatedBy As String
    Public Property DateCreated As Nullable(Of Date)
    Public Property ModifBy As String
    Public Property DateModif As Nullable(Of Date)

End Class
Partial Public Class users_SGCT
    Public Property id As Integer
    Public Property nom As String
    Public Property prenom As String
    Public Property adresse As String
    Public Property Telephone As String
    Public Property username As String
    Public Property password As String
    Public Property occupation As Integer
    Public Property IsActif As Integer

End Class
Partial Public Class sp_all_inspection_Result
    Public Property Nom_entreprise As String
    Public Property Id_entreprise As Nullable(Of Long)
    Public Property INSPECTIO_BY As String
    Public Property id_produit As Nullable(Of Long)
    Public Property DATEINSPECTION_CREATED As Nullable(Of Date)
    Public Property nom_produit As String

End Class
Partial Public Class sp_all_patente_Result
    Public Property id_anneefiscale As Nullable(Of Long)
    Public Property description As String
    Public Property Debut As Nullable(Of Date)
    Public Property fin As Nullable(Of Date)
    Public Property ID_Statut As Nullable(Of Long)
    Public Property Statut As String
    Public Property descriptition As String
    Public Property Id_entreprise As Long
    Public Property Nom_entreprise As String
    Public Property Noms_anterieurs As String
    Public Property Forme_juridique As Nullable(Of Long)
    Public Property Tel2 As String
    Public Property Tel1 As String
    Public Property descritption As String
    Public Property Adresse As String
    Public Property autreAdresse As String
    Public Property DateCreated As Date
    Public Property CreatedBy As String
    Public Property DateModif As Nullable(Of Date)
    Public Property Fondateur As String
    Public Property DebutdateFonctionnement As Nullable(Of Date)
    Public Property ID_Forme As Nullable(Of Long)
    Public Property Nom_forme As String
    Public Property Expr1 As String
    Public Property ID_Patente As Long
    Public Property Expr2 As Nullable(Of Long)
    Public Property Id_AnneeFiscal As Nullable(Of Long)
    Public Property Id_commune As Nullable(Of Long)
    Public Property MasseSalariale As Nullable(Of Decimal)
    Public Property ChiffresAffaires As Nullable(Of Decimal)
    Public Property Commentaire As String
    Public Property id_Facture As Nullable(Of Long)
    Public Property Expr3 As Nullable(Of Long)
    Public Property id_secteur As Nullable(Of Long)
    Public Property Montant As Nullable(Of Decimal)

End Class
Partial Public Class sp_event_Result
    Public Property nom_monument As String
    Public Property Statut As String
    Public Property nom_mairie As String
    Public Property ID_Evaluation As Long
    Public Property ID_monument As Nullable(Of Long)
    Public Property Commentaires As String
    Public Property ID_Institution As Nullable(Of Long)
    Public Property DateEffectuee As Nullable(Of Date)
    Public Property DateDebut As Nullable(Of Date)
    Public Property DateFin As Nullable(Of Date)
    Public Property Sujet As String
    Public Property Description As String

End Class
Partial Public Class sp_mairie_monument_Result
    Public Property nom_mairie As String
    Public Property Id_mairie As Nullable(Of Long)
    Public Property description As String
    Public Property Id_monument As Long
    Public Property nom_monument As String
    Public Property Expr1 As String

End Class
Partial Public Class sp_patente_Result
    Public Property Id_entreprise As Long
    Public Property Nom_entreprise As String
    Public Property Noms_anterieurs As String
    Public Property Forme_juridique As Nullable(Of Long)
    Public Property Tel1 As String
    Public Property Tel2 As String
    Public Property descritption As String
    Public Property Adresse As String
    Public Property autreAdresse As String
    Public Property DateCreated As Date
    Public Property CreatedBy As String
    Public Property DateModif As Nullable(Of Date)
    Public Property ModifBy As String
    Public Property Fondateur As String
    Public Property DebutdateFonctionnement As Nullable(Of Date)
    Public Property id_anneefiscale As Nullable(Of Long)
    Public Property description As String
    Public Property Debut As Nullable(Of Date)
    Public Property fin As Nullable(Of Date)
    Public Property Createdby1 As String
    Public Property DateCreated1 As Nullable(Of Date)
    Public Property ModifBy1 As String
    Public Property DateModif1 As Nullable(Of Date)
    Public Property id_Municipalite As Nullable(Of Long)
    Public Property ID_Forme As Nullable(Of Long)
    Public Property Nom_forme As String
    Public Property descriptition As String
    Public Property CreatedBy2 As String
    Public Property DateCreated2 As Nullable(Of Date)
    Public Property ModifBy2 As String
    Public Property DateModif2 As Nullable(Of Date)
    Public Property ID_Patente As Long
    Public Property ID_Entreprise1 As Nullable(Of Long)
    Public Property Id_AnneeFiscal As Nullable(Of Long)
    Public Property Id_commune As Nullable(Of Long)
    Public Property MasseSalariale As Nullable(Of Decimal)
    Public Property ChiffresAffaires As Nullable(Of Decimal)
    Public Property Commentaire As String
    Public Property id_Facture As Nullable(Of Long)
    Public Property DateCreated3 As Nullable(Of Date)
    Public Property CreatedBy3 As String
    Public Property DateModif3 As Nullable(Of Date)
    Public Property ModifBy3 As String
    Public Property Montant As Nullable(Of Decimal)

End Class
Partial Public Class sp_patente_statut_Result
    Public Property id_anneefiscale As Nullable(Of Long)
    Public Property description As String
    Public Property Debut As Nullable(Of Date)
    Public Property fin As Nullable(Of Date)
    Public Property ID_Statut As Nullable(Of Long)
    Public Property Statut As String
    Public Property descriptition As String
    Public Property Id_entreprise As Long
    Public Property Nom_entreprise As String
    Public Property Noms_anterieurs As String
    Public Property Forme_juridique As Nullable(Of Long)
    Public Property Tel2 As String
    Public Property Tel1 As String
    Public Property descritption As String
    Public Property Adresse As String
    Public Property autreAdresse As String
    Public Property DateCreated As Date
    Public Property CreatedBy As String
    Public Property DateModif As Nullable(Of Date)
    Public Property Fondateur As String
    Public Property DebutdateFonctionnement As Nullable(Of Date)
    Public Property ID_Forme As Nullable(Of Long)
    Public Property Nom_forme As String
    Public Property Expr1 As String
    Public Property ID_Patente As Long
    Public Property Expr2 As Nullable(Of Long)
    Public Property Id_AnneeFiscal As Nullable(Of Long)
    Public Property Id_commune As Nullable(Of Long)
    Public Property MasseSalariale As Nullable(Of Decimal)
    Public Property ChiffresAffaires As Nullable(Of Decimal)
    Public Property Commentaire As String
    Public Property id_Facture As Nullable(Of Long)
    Public Property Expr3 As Nullable(Of Long)
    Public Property id_secteur As Nullable(Of Long)
    Public Property Montant As Nullable(Of Decimal)

End Class
