'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class SGCT_dbEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=SGCT_dbEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Tbl_secteur_activite() As DbSet(Of Tbl_secteur_activite)
    Public Overridable Property Tbl_statut_patente() As DbSet(Of Tbl_statut_patente)
    Public Overridable Property Tbl_statut_occupant() As DbSet(Of Tbl_statut_occupant)
    Public Overridable Property tbl_RefNiveauGeo() As DbSet(Of tbl_RefNiveauGeo)
    Public Overridable Property tbl_RefUniteGeo() As DbSet(Of tbl_RefUniteGeo)
    Public Overridable Property tbl_annee_fiscale() As DbSet(Of tbl_annee_fiscale)
    Public Overridable Property Tbl_forme_juridique() As DbSet(Of Tbl_forme_juridique)
    Public Overridable Property tbl_Entreprise() As DbSet(Of tbl_Entreprise)
    Public Overridable Property tbl_Patente() As DbSet(Of tbl_Patente)
    Public Overridable Property users_SGCT() As DbSet(Of users_SGCT)
    Public Overridable Property Tbl_nombre() As DbSet(Of Tbl_nombre)
    Public Overridable Property Tbl_type_annexe() As DbSet(Of Tbl_type_annexe)
    Public Overridable Property Tbl_architecte() As DbSet(Of Tbl_architecte)
    Public Overridable Property tbl_monument() As DbSet(Of tbl_monument)
    Public Overridable Property tbl_mairie() As DbSet(Of tbl_mairie)
    Public Overridable Property Tbl_Statut_Evenement() As DbSet(Of Tbl_Statut_Evenement)
    Public Overridable Property Tbl_Event() As DbSet(Of Tbl_Event)
    Public Overridable Property tbl_raison_arbattage() As DbSet(Of tbl_raison_arbattage)
    Public Overridable Property tbl_statut_arbattage() As DbSet(Of tbl_statut_arbattage)
    Public Overridable Property tbl_formulaire_arbattage() As DbSet(Of tbl_formulaire_arbattage)
    Public Overridable Property Tbl_Personne() As DbSet(Of Tbl_Personne)
    Public Overridable Property Tbl_Inspection() As DbSet(Of Tbl_Inspection)
    Public Overridable Property Tbl_Produit() As DbSet(Of Tbl_Produit)

    Public Overridable Function sp_patente() As ObjectResult(Of sp_patente_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_patente_Result)("sp_patente")
    End Function

    Public Overridable Function sp_all_patente() As ObjectResult(Of sp_all_patente_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_all_patente_Result)("sp_all_patente")
    End Function

    Public Overridable Function sp_patente_statut(iD_Statut As Nullable(Of Long)) As ObjectResult(Of sp_patente_statut_Result)
        Dim iD_StatutParameter As ObjectParameter = If(iD_Statut.HasValue, New ObjectParameter("ID_Statut", iD_Statut), New ObjectParameter("ID_Statut", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_patente_statut_Result)("sp_patente_statut", iD_StatutParameter)
    End Function

    Public Overridable Function sp_mairie_monument() As ObjectResult(Of sp_mairie_monument_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_mairie_monument_Result)("sp_mairie_monument")
    End Function

    Public Overridable Function sp_event() As ObjectResult(Of sp_event_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_event_Result)("sp_event")
    End Function

    Public Overridable Function sp_all_inspection() As ObjectResult(Of sp_all_inspection_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_all_inspection_Result)("sp_all_inspection")
    End Function

End Class
